server:
  port: 8081
spring:
  mail:
    host: smtp.qq.com
    username: 982908910@qq.com
    password: mdbpnmpygtvbbdhe
    default-encoding: UTF-8
    properties:
     mail:
      smtp:
       auth: true
       starttls:
         enable: true
         required: true
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.105.174.248:3306/car_rental?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: first.pojo
qiniu:
  accessKey: m7mFmCTX55PMNPkEBaOLFQMLxW4ZFfZwf2EBm1M2
  secretKey: dn220PqIs813-IYrIZtzO_bGLXPo3QSVNep6wNty
  bucket:  1908-picture
  url: http://q1arif8n1.bkt.clouddn.com/


