spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.105.174.248:3306/my_shiro?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true

qiniu:
  accessKey: m7mFmCTX55PMNPkEBaOLFQMLxW4ZFfZwf2EBm1M2
  secretKey: dn220PqIs813-IYrIZtzO_bGLXPo3QSVNep6wNty
  bucket:  1908-picture
  url: http://q1arif8n1.bkt.clouddn.com/

mybatis:
  mapper-locations: classpath:mapper/*.xml